modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "dragonflame"
version = "${version}"
displayName = "Dragonflame"
authors = "satisfy, Cristelknight, cph101, ecacresasson, baumeisterjo"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
logoFile = "pack.png"

[[dependencies.dragonflame]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dragonflame]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dragonflame]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.dragonflame]]
modId="smartbrainlib"
mandatory=true
versionRange="[1.8,)"
ordering="NONE"
side="SERVER"